[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'rm -f package-lock.json',
  'npm install --no-package-lock --production=false'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'
